# Generated by Django 3.2 on 2021-05-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_item',
        ),
    ]
