# Generated by Django 3.2 on 2021-05-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
