# Generated by Django 3.2 on 2021-05-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210506_1847'),
        ('carts', '0008_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
            preserve_default=False,
        ),
    ]
