# Generated by Django 3.2 on 2021-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cart_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='items_order',
            field=models.BooleanField(default=False),
        ),
    ]
