# Generated by Django 3.2 on 2021-04-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_food_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота:'),
        ),
    ]
