# Generated by Django 3.2 on 2021-04-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210426_0330'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='food',
            index_together={('id',)},
        ),
    ]
