# Generated by Django 3.2 on 2021-04-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_food_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='food',
            index_together=set(),
        ),
    ]
