# Generated by Django 3.2 on 2021-05-02 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.food', verbose_name='Пользователь:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название:')),
                ('description', models.TextField(blank=True, verbose_name='Описание:')),
                ('price', models.PositiveIntegerField(verbose_name='Цена:')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во:')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото:')),
                ('Basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.basket', verbose_name='Пользователь:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
