# Generated by Django 3.2 on 2021-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210505_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.IntegerField(choices=[(1, 'Кафе/кофейня/бар'), (2, 'Ресторан'), (3, 'Столовая'), (4, 'Гостиница'), (5, 'Местный производитель'), (6, 'Местный фермер'), (7, 'Магазин «у дома»'), (8, 'Гипермаркет'), (9, 'Cash&Carry'), (10, 'Прилавок/киоск'), (11, 'Частное лицо')], verbose_name='Тип компании:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Широта:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='lon',
            field=models.FloatField(default=0.0, verbose_name='Долгота:'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.IntegerField(choices=[(1, 'Мясо и мясопродукты'), (2, 'Рыба и морепродукты'), (3, 'Молоко и молокопродукты'), (4, 'Овощи и фрукты'), (5, 'Пекарня'), (6, 'Кондитерская'), (7, 'Консервы'), (8, 'Бакалея'), (9, 'Кулинария'), (10, 'Частное лицо')], verbose_name='Тип продукта:'),
        ),
    ]
