# Generated by Django 3.2 on 2021-05-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210506_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Старая цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.IntegerField(choices=[(1, 'Мясо и мясопродукты'), (2, 'Рыба и морепродукты'), (3, 'Молоко и молокопродукты'), (4, 'Овощи и фрукты'), (5, 'Пекарня'), (6, 'Кондитерская'), (7, 'Консервы'), (8, 'Бакалея'), (9, 'Кулинария')], verbose_name='Тип продукта:'),
        ),
    ]
