# Generated by Django 3.2 on 2021-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210508_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='images/company.jpg', upload_to='images', verbose_name='Фото:'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='images/food.jpg', upload_to='images', verbose_name='Фото:'),
        ),
        migrations.AlterField(
            model_name='review',
            name='data_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
