# Generated by Django 3.2 on 2021-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_alter_trash_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='image',
            field=models.ImageField(default='images/1.jpg', upload_to='images', verbose_name='Фото:'),
        ),
    ]
