# Generated by Django 3.2 on 2021-05-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210526_1541'),
        ('waste', '0006_alter_trash_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='image',
            field=models.ImageField(default='images/trash.jpg', upload_to='images', verbose_name='Фото:'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.profile', verbose_name='Пользователь:'),
        ),
    ]
