# Generated by Django 3.2 on 2021-05-26 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste', '0008_alter_trash_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='price',
        ),
        migrations.AddField(
            model_name='trash',
            name='period',
            field=models.TextField(blank=True, verbose_name='Период:'),
        ),
        migrations.AddField(
            model_name='trash',
            name='point',
            field=models.CharField(blank=True, max_length=128, verbose_name='Адрес:'),
        ),
        migrations.AddField(
            model_name='trash',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Телефон:'),
        ),
        migrations.AddField(
            model_name='trash',
            name='username',
            field=models.CharField(default=1, max_length=128, verbose_name='Имя:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trash',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название отходов:'),
        ),
        migrations.CreateModel(
            name='TrashGive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название отходов:')),
                ('username', models.CharField(max_length=128, verbose_name='Имя:')),
                ('description', models.TextField(blank=True, verbose_name='Описание:')),
                ('period', models.TextField(blank=True, verbose_name='Период:')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во:')),
                ('telephone', models.CharField(max_length=11, verbose_name='Телефон:')),
                ('date', models.DateTimeField(verbose_name='К какому дню')),
                ('point', models.CharField(blank=True, max_length=128, verbose_name='Адрес:')),
                ('image', models.ImageField(default='images/trash.jpg', upload_to='images', verbose_name='Фото:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь:')),
            ],
        ),
    ]
