# Generated by Django 3.2 on 2021-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0009_auto_20210526_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashgive',
            name='date',
            field=models.DateField(verbose_name='К какому дню'),
        ),
    ]
